/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.andihasan7.salamSapa

class Sapa {
    fun salamSapa(name: String): String = "hai $name, selamat datang di Indo****t :)"
}
